# Generated by Django 4.1.3 on 2022-11-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycpi',
            name='cpi_internal_code',
            field=models.TextField(default=''),
        ),
    ]
