# Generated by Django 4.1.3 on 2022-11-20 22:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inflation', '0003_alter_monthlycpi_cpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycpi',
            name='monthly_cpi_id',
            field=models.UUIDField(default=uuid.UUID('0f6cdd2a-230f-41dd-814b-2c0f0f530e9e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
