# Generated by Django 4.1.3 on 2022-11-20 22:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inflation', '0004_alter_monthlycpi_monthly_cpi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycpi',
            name='monthly_cpi_id',
            field=models.UUIDField(default=uuid.UUID('2a8817f7-6922-11ed-844e-d8c0a68453de'), editable=False, primary_key=True, serialize=False),
        ),
    ]
