# Generated by Django 4.1.3 on 2022-11-20 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inflation', '0005_alter_monthlycpi_monthly_cpi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycpi',
            name='monthly_cpi_id',
            field=models.TextField(default=uuid.UUID('4994e3a2-e47a-43a0-a4af-8616c03569c8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
