# Generated by Django 4.1.3 on 2022-11-27 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inflation', '0006_alter_monthlycpi_monthly_cpi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycpi',
            name='cpi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlycpi',
            name='monthly_cpi_id',
            field=models.TextField(default=uuid.UUID('8f650ae9-cb66-4769-b446-cbefd7efd36e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
